### ISSUE TITLE
To use pkgrepo.managed instead of file.replace for disable or enable repo

### ISSUE THREAD

**Issue by alisson276** [saltstack-formulas/epel-formula#34]
Using file.replace to disable or enable EPEL repo has a problem because in the file /etc/yum.repos.d/epel.repo there are 3 repos, not just 1. So, if pillar "epel:disabled" is False the repos epel, epel-debuginfo and epel-source are enabled when I just wanna enable epel repo.

**Comment by alisson276** [comment]
Some like this:
```
disable_epel:
  pkgrepo.managed:
    - name: epel
    - enabled: False
```
